### ISSUE TITLE
Small Bugs #2

### ISSUE THREAD

**Issue by TotoR115** [AngelGryph/MadeInHeaven_EncountersAndQuests#6]
There is 1 issue with `animations.2da` that prevent some component to install if IAvb5 is installed: 
the line : 
> mh#bwght	   wight_barrow		   **barrow_wight**		   vampire

should be : 
> mh#bwght	wight_barrow	**wight_barrow**   vampire

In addition there is minor typo in `hentolds_dagger.tpa`:
the line:
>    patch_ability_inline=> ~ to_hit=>1 damage_bonus=>1 ability_icon=>"**mh#nesdg**"~

should be: 
> patch_ability_inline=>~ to_hit=>1 damage_bonus=>1 ability_icon=>"**mh#hendg**"~

**Comment by TotoR115** [comment]
in addition in  `animations.2da` the `mh#wght7` line could be with IAvb5 installed:

> wight_green		**WIGHT_LESSER**		revenant

instead of :

> wight_green		**wight_gray**		revenant

**Comment by TotoR115** [comment]
in `ids_entries.2da`, the following line create CTD:

animate	ELEMENTAL_WATER			0xE24D
animate	ELEMENTAL_WATER_SMALL		0xE26D

for oBG2 (with IA) it should be:
animate	ELEMENTAL_WATER			0x5039
animate	ELEMENTAL_WATER_SMALL		0x5011

But without IA all should be: 
animate	WATER_WEIRD			0xEF10

so it seems that you should have them like others in animation.2da

**Comment by AngelGryph** [comment]
I only marginally support oBG2, IA or not, so I won't do extensive testing.  However, these should be fixed in the current master.

Specifically, I did the following:
- Animation compatibility code is now gathered in mih_eq/shared/compat/fix_animations.tpa.
- Changed lib_ids to no longer overwrite existing entries.
- Updated animations.2da as you suggested.
- Water elemental variants are directly cloned from the existing elwatg01.cre.
- The mod now creates a list of animations used in weidu_external/data/mih_eq/animations.txt.

Note that IA support is still off by default and needs to be explicitly enabled in the .ini file.
